services:
  bot:
    build: .
    image: menand-antispam:latest
    container_name: menand-antispam
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
